// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: false },
  experimental: {
    inlineSSRStyles: true,
  },
  compatibilityDate: '2026-03-12',
  modules: [
    "@nuxtjs/tailwindcss",
    "@nuxtjs/google-fonts",
    "@nuxt/content",
    "nuxt-llms",
    "@nuxt/image",
    "@nuxtjs/i18n",
    "@nuxtjs/sitemap",
  ],
  runtimeConfig: {
    public: {
      api: process.env.API_DOMAIN || "",
      location: process.env.LOCATION_API || "",
      app: process.env.APP_DOMAIN || "",
      gtmKey: process.env.GTM_KEY || "",
      gtmDebug: process.env.GTM_DEBUG || "",
      discordLink: process.env.DISCORD_LINK || "",
      email: process.env.EMAIL || "hello@kanka.io",
      emailLink: process.env.EMAIL_LINK || "mailto:hello@kanka.io",
    },
  },
  googleFonts: {
    families: {
      Poppins: [400, 500, 700, 800],
    },
    // Optimizations
    display: 'swap',
    prefetch: true,           // DNS lookup early
    preconnect: true,         // Establish connection early
    preload: true,            // Preload font files
    subsets: ['latin'],        // Only Latin characters
  },
  css: [
    "~/assets/css/colors.css",
    "~/assets/css/fonts.css",
    "~/assets/fontawesome/css/fontawesome.css",
    "~/assets/fontawesome/css/solid.css",
  ],
  //preset: 'netlify',
  target: "static",
  ssr: true,
  routeRules: {
    "/": { prerender: true },
    "/pricing": { prerender: true },
    "/features": { prerender: true },
    "/learn/**": { prerender: true },
    "/use-cases/**": { prerender: true },
    "/worldbuilding-guides/**": { prerender: true },

    // Social redirects
    "/go/discord": { redirect: { to: "https://discord.gg/rhsyZJ4", statusCode: 301 } },
    "/go/instagram": { redirect: { to: "https://www.instagram.com/kanka.io/", statusCode: 301 } },
    "/go/reddit": { redirect: { to: "https://www.reddit.com/r/kanka", statusCode: 301 } },
    "/go/twitter": { redirect: { to: "https://twitter.com/kankaio", statusCode: 301 } },
    "/go/facebook": { redirect: { to: "https://www.facebook.com/kanka.io.ch", statusCode: 301 } },
    "/go/youtube": { redirect: { to: "https://www.youtube.com/c/kankaio/videos", statusCode: 301 } },
    "/go/twitch": { redirect: { to: "https://twitch.tv/kankaio", statusCode: 301 } },
    "/go/github": { redirect: { to: "https://github.com/owlchester/kanka", statusCode: 301 } },

    // Comparison redirect
    "/comparison": { redirect: { to: "/kanka-vs-worldanvil", statusCode: 301 } },
    "/comparison/**": { redirect: { to: "/kanka-vs-worldanvil", statusCode: 301 } },

    // Old locale paths → /gone (410 served by that page)
    "/it/**": { redirect: { to: "/gone", statusCode: 301 } },
    "/ru/**": { redirect: { to: "/gone", statusCode: 301 } },
    "/sk/**": { redirect: { to: "/gone", statusCode: 301 } },
    "/nl/**": { redirect: { to: "/gone", statusCode: 301 } },
    "/gl/**": { redirect: { to: "/gone", statusCode: 301 } },
    "/hr/**": { redirect: { to: "/gone", statusCode: 301 } },
    "/he/**": { redirect: { to: "/gone", statusCode: 301 } },
    "/ca/**": { redirect: { to: "/gone", statusCode: 301 } },
    "/pl/**": { redirect: { to: "/gone", statusCode: 301 } },
  },
  nitro: {
    prerender: {
        crawlLinks: true,
        failOnError: false,
        autoSubfolderIndex: false,
        routes: [
            // English (no prefix)
            "/use-cases/game-masters",
            "/use-cases/worldbuilders",
            "/use-cases/players",
            "/use-cases/writers",
            "/use-cases/content-creators",
            "/worldbuilding-guides/start-creating-your-world",
            "/worldbuilding-guides/how-much-worldbuilding-do-you-really-need",
            "/learn/worldbuilding",
            "/learn/hierarchies",
            "/learn/characters",
            "/learn/factions",
            "/learn/prep",
            "/learn/players",
            "/learn/living-web",
            // French
            "/fr/learn/worldbuilding",
            "/fr/learn/hierarchies",
            "/fr/learn/characters",
            "/fr/learn/factions",
            "/fr/learn/prep",
            "/fr/learn/players",
            "/fr/learn/living-web",
            "/fr/use-cases/game-masters",
            "/fr/use-cases/worldbuilders",
            "/fr/use-cases/players",
            "/fr/use-cases/writers",
            "/fr/use-cases/content-creators",
            "/fr/worldbuilding-guides/start-creating-your-world",
            "/fr/worldbuilding-guides/how-much-worldbuilding-do-you-really-need",
            // German
            "/de/learn/worldbuilding",
            "/de/learn/hierarchies",
            "/de/learn/characters",
            "/de/learn/factions",
            "/de/learn/prep",
            "/de/learn/players",
            "/de/learn/living-web",
            "/de/use-cases/game-masters",
            "/de/use-cases/worldbuilders",
            "/de/use-cases/players",
            "/de/use-cases/writers",
            "/de/use-cases/content-creators",
            "/de/worldbuilding-guides/start-creating-your-world",
            "/de/worldbuilding-guides/how-much-worldbuilding-do-you-really-need",
            // Spanish
            "/es/learn/worldbuilding",
            "/es/learn/hierarchies",
            "/es/learn/characters",
            "/es/learn/factions",
            "/es/learn/prep",
            "/es/learn/players",
            "/es/learn/living-web",
            "/es/use-cases/game-masters",
            "/es/use-cases/worldbuilders",
            "/es/use-cases/players",
            "/es/use-cases/writers",
            "/es/use-cases/content-creators",
            "/es/worldbuilding-guides/start-creating-your-world",
            "/es/worldbuilding-guides/how-much-worldbuilding-do-you-really-need",
            // Portuguese BR
            "/pt-BR/learn/worldbuilding",
            "/pt-BR/learn/hierarchies",
            "/pt-BR/learn/characters",
            "/pt-BR/learn/factions",
            "/pt-BR/learn/prep",
            "/pt-BR/learn/players",
            "/pt-BR/learn/living-web",
            "/pt-BR/use-cases/game-masters",
            "/pt-BR/use-cases/worldbuilders",
            "/pt-BR/use-cases/players",
            "/pt-BR/use-cases/writers",
            "/pt-BR/use-cases/content-creators",
            "/pt-BR/worldbuilding-guides/start-creating-your-world",
            "/pt-BR/worldbuilding-guides/how-much-worldbuilding-do-you-really-need",
        ],
    },
  },
  llms: {
    domain: "https://kanka.io",
    title: "Kanka",
    description: "Collaborative RPG campaign management and worldbuilding software",
  },
  i18n: {
    locales: [
      { code: 'en', language: 'en-US', name: 'English', file: 'en.json' },
      { code: 'fr', language: 'fr-FR', name: 'Français', file: 'fr.json' },
      { code: 'de', language: 'de-DE', name: 'Deutsch', file: 'de.json' },
      { code: 'es', language: 'es-ES', name: 'Español', file: 'es.json' },
      { code: 'pt-BR', language: 'pt-BR', name: 'Português (BR)', file: 'pt-BR.json' },
    ],
    defaultLocale: 'en',
    baseUrl: 'https://kanka.io',
    strategy: 'prefix_except_default',
    lazy: true,
    langDir: '../locales/',
    detectBrowserLanguage: false,
    compilation: {
      strictMessage: false,
    },
  },
  site: {
    url: 'https://kanka.io',
  },
  sitemap: {
    sources: ['/api/__sitemap__/urls'],
    exclude: [
      '/gone',
      '/goodbye',
      '/privacy-policy',
      '/terms-and-conditions',
    ],
  },
  image: {
    format: ["webp"],
  },
});
